platform:
  - x64
environment:
  global:
    TWINE_USERNAME: __token__
  matrix:
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"

install: 
  - set PATH=%PYTHON%;%PATH%
  - "python.exe -m pip install --upgrade pip"
  - choco install protoc
  - choco install rust

build_script: 
  - cd bindings-python
  - "python.exe setup.py bdist_wheel"
  - ls dist

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
