platform:
  - x64
environment:
  global:
    TWINE_USERNAME: __token__
  matrix:
    - PYTHON: "C:\\Python38"
    # - PYTHON: "C:\\Python38-x64"

install: 
  - dir C:\OpenSSL-v111-Win32\bin
  - dir C:\OpenSSL-v111-Win32\
  - choco install protoc
  - choco install mingw
  - choco install rust
  - refreshenv
  - set PATH=%PYTHON%;%PATH%
  - set OPENSSL_DIR=C:\OpenSSL-v111-Win32
  - "python.exe -m pip install wheel"

build_script: 
  - cd bindings-python
  - "python.exe setup.py sdist bdist_wheel"
  - ls dist

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
