platform:
  - x64
environment:
  global:
    TWINE_USERNAME: __token__

  matrix:
    - compiler: msys2
      ARCH: x64
      PYTHON: "C:\\Python38-x64"
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
    # - compiler: msys2
    #   ARCH: x86
    #   PYTHON: "C:\\Python38"
    #   MSYS2_ARCH: i686
    #   MSYS2_DIR: msys64
    #   MSYSTEM: MINGW32
    # - compiler: cygwin

install: 
  - choco install protoc
  - choco install rust
  - refreshenv
  - set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PYTHON%;%PATH%
  - set OPENSSL_DIR=C:\\OpenSSL-v111-Win64
  - "python.exe -m pip install wheel"

  - bash -lc "pacman --noconfirm --sync --refresh pacman"
  - bash -lc "pacman --noconfirm --sync --refresh --sysupgrade"

# rem bash -xlc "pacman --noconfirm -S --needed base-devel"

  - bash -xlc "pacman --noconfirm -S --needed pacman-mirrors"
  - bash -xlc "pacman --noconfirm -S --needed diffutils make mingw-w64-%MSYS2_ARCH%-gcc"

build_script: 
  - cd bindings-python
  - "python.exe setup.py sdist bdist_wheel"
  - ls dist

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
